### ISSUE TITLE
Permissions on polymorphic relationships

### ISSUE THREAD

**Issue by urkle** [stffn/declarative_authorization#114]
Given the Models

``` ruby
def Event < ActiveRecord::Base
  belongs_to :eventable, :polymorphic => true
end
def Fruit < ActiveRecord::Base
   has_many :events, :as => :eventable, :dependent => :destroy
end
def Snack < ActiveRecord::Base
   has_many :events, :as => :eventable, :dependent => :destroy
end
```

And Authorization rules

``` ruby
authorization do
  role :user do
     has_permission_on :fruits, :to => :manage
     has_permission_on :events, :to => :manage do
       if_permitted_to :read, :eventable
     end
  end
end
```

And seed

``` ruby
apple = Fruit.create :name => 'Apple'
apple_event apple.events.create :subject => 'Create', :type =>
'Create'
cookie = Snack.create :name => 'Cookie'
cookie_event = cookie.events.create :subject => 'Create', :type =>
'Create'
```

These work

``` ruby
permitted_to? :edit, apple
permitted_to? :edit, apple_event 
```

And these do not

``` ruby
permitted_to? :edit, cookie
permitted_to? :edit, cookie_event 
```

And this blows up with the call to `Event.with_permissions_to(:read)

Your suggestion was to try

``` ruby
     has_permission_on :fruits, :to => :manage
     has_permission_on :events, :to => :manage do
       if_permitted_to :read, :eventable, :context => :fruits
       if_permitted_to :read, :eventable, :context => :snacks
     end 
```

However this does not work, it simply fails even more miserably that before.

Currently my workaround is the following.

``` ruby
def Event <Active Record::Base
  belongs_to :eventable, :polymorphic => true

  def self.with_permissions_to(permission, *args)
    options = args.extract_options!.dup

    self.all(options).select do |e|
      e.permitted_to? permission
    end
  end
end
```

**Comment by derekatkins** [comment]
I'm still seeing this issue.  unfortunately the workaround does not work for me because I need an AR::Relation in order for things like limit() to work _after_ the permission checks.  When I use :context I get:

You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.length

and the backtrace looks like:

declarative_authorization (0.5.5) lib/declarative_authorization/obligation_scope.rb:120:in `follow_comparison'
declarative_authorization (0.5.5) lib/declarative_authorization/obligation_scope.rb:87:in`follow_path'
declarative_authorization (0.5.5) lib/declarative_authorization/obligation_scope.rb:81:in `each'
declarative_authorization (0.5.5) lib/declarative_authorization/obligation_scope.rb:81:in`follow_path'
declarative_authorization (0.5.5) lib/declarative_authorization/obligation_scope.rb:69:in `parse!'
declarative_authorization (0.5.5) lib/declarative_authorization/in_model.rb:76:in`obligation_scope_for'
declarative_authorization (0.5.5) lib/declarative_authorization/in_model.rb:75:in `each'
declarative_authorization (0.5.5) lib/declarative_authorization/in_model.rb:75:in`obligation_scope_for'
declarative_authorization (0.5.5) lib/declarative_authorization/in_model.rb:124:in `with_permissions_to'
activerecord (3.1.3) lib/active_record/relation.rb:455:in`send'
activerecord (3.1.3) lib/active_record/relation.rb:455:in `method_missing'
activerecord (3.1.3) lib/active_record/relation.rb:180:in`scoping'
activerecord (3.1.3) lib/active_record/base.rb:1196:in `with_scope'
activerecord (3.1.3) lib/active_record/relation.rb:180:in`send'
activerecord (3.1.3) lib/active_record/relation.rb:180:in `scoping'
activerecord (3.1.3) lib/active_record/relation.rb:455:in`method_missing'
app/models/event.rb:23:in `my_events'
...

**Comment by stffn** [comment]
To solve this issue, we really need a failing test case

**Comment by derekatkins** [comment]
I can reduce my existing app to create a minimal app that shows the issue -- is that sufficient for you to generate an actual test case?
