### ISSUE TITLE
attribute_check => true for a namespaced resource is not working

### ISSUE THREAD

**Issue by tvdeyen** [stffn/declarative_authorization#118]
Sorry, but your whole instance variable setting and before_filter workflow has completely changed. (In a wrong way IMHO, btw.)

Could you please update the readme!

Thanks!

**Comment by stffn** [comment]
Not sure what you are referring to.  Could you be more specific or provide a patch?

**Comment by tvdeyen** [comment]
In your README you are saying that one can set the instance variable for a resource, if using the `attribute_check` together with `filter_access_to`. 

And that you will use this instance variable for the attribute check.

But this is not true!

You are actually not even checking for its existence in your app:

https://github.com/stffn/declarative_authorization/blob/master/lib/declarative_authorization/in_controller.rb#L633

One has to pass the `load_method` parameter.

And even worse. Using `filter_resource_access` one can't even pass a `load_method`.

So one has to use `filter_access_to :all` and then pass the `load_method` for all resourceful actions by hand!

Not even setting the `load_blah` method in a `before_filter` is working!

Understanding this whole `attribute_check` thing costs me hours of work.

Sorry for these harsh words. But that really pissed me off.

So please update you readme and wiki files!

**Comment by stffn** [comment]
If this does not work, it is a bug -- so it's not the README's fault here.  However, in the tests it works.  And you do not need load_method for filter_resource_access, but can define the respective load method to override the default behavior.  Also, the lines you were looking for in the code are rather 640--642.

**Comment by tvdeyen** [comment]
Once again:

I followed your README and implemented this:

```

module Alchemy
    class ElementsController < Alchemy::BaseController

        before_filter :load_element, :only => :show
        filter_access_to :show, :attribute_check => true, :context => 'Alchemy::Element'
        layout false

        # Returns the element partial as HTML or as JavaScript that tries to replace a given +container_id+ with the partial content via jQuery.
        def show
            @page = @element.page
            respond_to do |format|
                format.html
                format.js
            end
        end

    private

        def load_element
            @element = Alchemy::Element.find(params[:id])
        end

    end
end
```

This raises an error `NameError (uninitialized constant Element):`

```
declarative_authorization (0.5.5) lib/declarative_authorization/in_controller.rb:639:in `load_object'
declarative_authorization (0.5.5) lib/declarative_authorization/in_controller.rb:616:in `permit!'
declarative_authorization (0.5.5) lib/declarative_authorization/in_controller.rb:113:in `block in filter_access_filter'
declarative_authorization (0.5.5) lib/declarative_authorization/in_controller.rb:113:in `each'
declarative_authorization (0.5.5) lib/declarative_authorization/in_controller.rb:113:in `all?'
declarative_authorization (0.5.5) lib/declarative_authorization/in_controller.rb:113:in `filter_access_filter'
```

In line 640 you are setting the instance variable with `underscore` without demodularizing it first. This causes a problem with namespaced resources. Because underscore on a namspaced resource returns `alchemy/element`, instead of `element`

If you change instance_var = `:"@#{load_object_model.name.underscore}"` to `instance_var = :"@#{load_object_model.name.demodulize.underscore}"` it will work.

I'll send you a pull request so can merge the changes.

And please update the README and mention the use of the `:context` option. Namespaced resources are widely used nowadays, especially in engines / mountable apps.

Maybe you could find a way for a build in namespace check. We solved it in Alchemy CMS [this way](https://github.com/magiclabs/alchemy_cms/blob/master/app/controllers/alchemy/admin/resources_controller.rb#L97)

**Comment by tvdeyen** [comment]
Now I ran into another issue. I just saw that you are using the context also for checking the permissions in the `authorization_rules.rb` file. So my workaround causes this error:

```
Permission denied: No matching rules found for show for #<Alchemy::User id: 1, firstname: "", lastname: "", login: "tvd", email: "tvd@magiclabs.de", gender: "", role: "admin", language: "de", crypted_password: "9375890b5fdc9327f2a1e41443b8adaa0e6bf29b66b9c9dbfa4...", password_salt: "2sAMiV57QTtLNbOymxNf", login_count: 30, failed_login_count: 0, last_request_at: "2012-02-07 10:40:02", current_login_at: "2012-02-07 08:46:30", last_login_at: "2012-02-06 12:29:48", current_login_ip: "127.0.0.1", last_login_ip: "127.0.0.1", persistence_token: "929413b94c8451e9a17423721b77ace5492baf7258265cd44d6...", single_access_token: "Q5H9TzpsU7vHWvDl2NTa", perishable_token: "DF304c8eFOT0ueUChJod", created_at: "2011-12-16 12:59:27", updated_at: "2012-02-07 10:40:02", creator_id: nil, updater_id: nil> (roles [:admin, :editor, :author, :registered, :guest], privileges [:show, :manage, :read], context "Alchemy::Element").
```

I have `alchemy_element` in my auth file:

```
has_permission_on :alchemy_elements, :to => [:show] do
  if_attribute :public => true
end
```

I fixed it with changing the auth file permission:

```
has_permission_on 'Alchemy::Element', :to => [:show] do
  if_attribute :public => true
end
```

But you definitely have to do something about the namespaced resources problem I think.
Mixing this both things into one option is not good IMHO.

**Comment by tvdeyen** [comment]
Oh boy, I also could have used the `model` option together with the `load_method` option and everything would have worked too. This leads me back to my original issue. Please update the README and Wiki Pages.

I'll reject my pull request and close this issue now.

**Comment by stffn** [comment]
I'll gladly review any suggestions on concrete changes to the documentation.  I think there is work necessary there.  Input in the form of pull request as the basis for discussion will speed up the improvements, of course.

**Comment by tvdeyen** [comment]
I know. But do you see this?:

https://github.com/magiclabs/alchemy_cms

So I know **exaclty** what you are talking about, but my time is also very limited and I have a lot of work with my own projects.

Sorry.
